Orgnization3 ali
YuejiaoShi/WFlance pull request #10
Opened 2024-11-11 23:09 UTC by AliRezaHassanloo2731

magdazelena and kristoffer advice done, pages folder added. client and developer folder created as a project main routes

2024-11-14 14:40 UTC, YuejiaoShi commented on node_modules/@kurkle/color/LICENSE.md
The node_modules should not be committed in any cases.

2024-11-14 14:40 UTC, YuejiaoShi commented on frontend/app/_pages/Header.js
Since we are using Next App Router, the ./_pages dir is not needed, and the files structure in this PR is wrong.

2024-11-15 13:18 UTC, magdazelena requested changes

2024-11-15 13:18 UTC, magdazelena commented on package.json
> +  }
what are those dependencies, they are not used in your components at all?

also, absoluletly make sure NOT to commit node_modules!!! Isn't that in your gitignore? gitignore should be commited as the team.

2024-11-17 11:12 UTC, closed without merging